services:

  whisper-asr-api:
    image: whisper-asr:1.0
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    restart: always
    volumes:
      - .cache/pip-docker/:/root/.cache/pip
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]